### ISSUE TITLE
Context Error in Untranslatable Spanish String

### ISSUE THREAD

**Issue by Aimarekin** [Alheimsins/b5-johnson-120-ipip-neo-pi-r#176]
The string "Back" used in the questionnaire to return to the previous page in Spanish is currently incorrectly translated as "Espalda", most likely due to a context issue.

"Espalda" in Spanish means the part of the body (the back), not the action (to go back). The correct translation would be "Atrás" (other words could also fit the context).

This string does not appear in the data folder. Perhaps it was translated manually by the developers with Google Translate, which would explain the lack of context.

**Comment by zrrrzzt** [comment]
Thank you for this information. I think you refer to the Big five webpage. The translation files are located here: https://github.com/rubynor/bigfive-web/blob/master/translations/es.js

If you have the time to take a look at the rest of the translation as well we would really appreciate it :-)
