### ISSUE TITLE
Need help with translations

### ISSUE THREAD

**Issue by maccyber** [Alheimsins/b5-johnson-120-ipip-neo-pi-r#25]
Need help with translations.

The test is currently translated to:
Finnish, Simplified Chinese, Thai, Italian, English, Norwegian, Spanish, Icelandic (partly), Dutch, Swedish (partly), Croatian, French, Estonian, German, Japanese, Urdru and Portuguese (brazil)

If you want to help by translating the items to other languages this is how you do it.
* clone the repo
* find a language you know in data
* duplicate the folder and rename it to the language you will translate
* use ISO 639-1 language code as folder name.
* translate the "text"-property for choices.js and questions.json
* don't change filenames, ids or any other properties
* add your language code to the data/languages.json file
* submit pull request
* happiness :-)

**Comment by MatheusMuriel** [comment]
Can I help translating to pt-br?

**Comment by zrrrzzt** [comment]
@MatheusMuriel Thank you for your interest, but we have an pt-br translation in place for this module.
We do however need help with translations for this module https://github.com/Alheimsins/b5-50-ipip-neo-pi-r and there pt-br is still not taken

**Comment by MatheusMuriel** [comment]
> 
> 
> @MatheusMuriel Thank you for your interest, but we have an pt-br translation in place for this module.
> We do however need help with translations for this module https://github.com/Alheimsins/b5-50-ipip-neo-pi-r and there pt-br is still not taken

I sent a PR, I'm not very experienced in translations, but I hope I have helped

**Comment by zrrrzzt** [comment]
Thx @MatheusMuriel I requested some minor changes but this is very helpful
